# This
D:\n\mylibsf4\00tsf\deeplearningchollet\deep-learning-with-python-meap-2nd-chapt01-07.pdf
2022-06-08

bookmark:
    chapter 2.2
    

In [ ]:
!python --version

In [2]:
!conda install -y  tensorflow 

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - tensorflow


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _tflow_select-2.3.0        |              mkl           2 KB
    absl-py-0.15.0             |     pyhd3eb1b0_0         103 KB
    aiohttp-3.8.1              |   py37h7f8727e_1         514 KB
    aiosignal-1.2.0            |     pyhd3eb1b0_0          12 KB
    astor-0.8.1                |   py37h06a4308_0          47 KB
    astunparse-1.6.3           |             py_0          17 KB
    async-timeout-4.0.1        |     pyhd3eb1b0_0          10 KB
    asynctest-0.13.0           |             py_0          26 KB
    attrs-21.4.0

In [3]:
%%bash
pwd
# conda init bash
# conda activate studiolab


/notebooks/keras635f


In [4]:
pip list

Package                 Version
----------------------- -----------
absl-py                 1.0.0
aiohttp                 3.8.1
aiosignal               1.2.0
albumentations          1.1.0
argcomplete             1.12.3
argon2-cffi             21.1.0
astor                   0.8.1
astunparse              1.6.3
async-timeout           4.0.1
asynctest               0.13.0
attrs                   21.4.0
backcall                0.2.0
beautifulsoup4          4.10.0
bleach                  4.1.0
blinker                 1.4
blis                    0.7.5
boto3                   1.20.4
botocore                1.23.4
bravado                 11.0.3
bravado-core            5.17.0
brotlipy                0.7.0
cachetools              4.2.4
captum                  0.4.1
catalogue               2.0.6
catalyst                21.10
certifi                 2022.5.18.1
cffi                    1.14.6
chardet                 4.0.0
charset-normalizer      2.0.4
click                   8.0.4
conda             

In [5]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [6]:
# 2.1 A first look at a neural network

train_images.shape

(60000, 28, 28)

In [7]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [8]:
from tensorflow.keras import models
from tensorflow.keras import layers
model = models.Sequential([
layers.Dense(512, activation='relu'),
layers.Dense(10, activation='softmax')
])

2022-06-10 02:26:09.895519: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-06-10 02:26:09.895932: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-06-10 02:26:09.898574: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [9]:
model.compile(optimizer='rmsprop',
loss='sparse_categorical_crossentropy',
metrics=['accuracy'])

In [10]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [11]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)
# Epoch 1/5
# 60000/60000 [==============================] - 5s - loss: 0.2524 - acc: 0.9273
# Epoch 2/5
# 51328/60000 [========================>.....] - ETA: 1s - loss: 0.1035 - acc: 0.9692

2022-06-10 02:26:51.299342: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2022-06-10 02:26:51.300181: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2600010000 Hz


Epoch 1/5
469/469 [==============================] - 11s 22ms/step - loss: 0.4327 - accuracy: 0.8744
Epoch 2/5
469/469 [==============================] - 8s 17ms/step - loss: 0.1118 - accuracy: 0.9680
Epoch 3/5
469/469 [==============================] - 8s 17ms/step - loss: 0.0735 - accuracy: 0.9783
Epoch 4/5
469/469 [==============================] - 6s 13ms/step - loss: 0.0491 - accuracy: 0.9856
Epoch 5/5
469/469 [==============================] - 6s 14ms/step - loss: 0.0371 - accuracy: 0.9890


In [12]:
# 2.1 A first look at a neural network
# Listing 2.6 Using the model to make predictions

test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]
# array([1.0726176e-10, 1.6918376e-10, 6.1314843e-08, 8.4106023e-06,
# 2.9967067e-11, 3.0331331e-09, 8.3651971e-14, 9.9999106e-01,
# 2.6657624e-08, 3.8127661e-07], dtype=float32)

array([9.6696784e-09, 6.0315690e-11, 6.3854918e-07, 2.1582387e-05,
       3.6327833e-12, 8.6368326e-09, 1.3802922e-14, 9.9997747e-01,
       1.7440261e-08, 1.8451753e-07], dtype=float32)

2.2 Data representations for neural networks
